version: '3.8'

services:
  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    working_dir: /app
    ports:
      - "3231:3231"
    environment:
      - MONGO_URI=mongodb://mongo:27017/eduapp
      - NODE_ENV=production
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo_data:
